<?php include 'header-section.php' ?>
<?php include 'nav-public.php' ?>
<?php include 'home-section.php' ?>
<?php include 'category-section.php' ?>
<?php include 'about-login-section.php' ?>
<?php include 'contact-section.php' ?>
<?php include 'filter-page.php' ?>
<?php include 'profile-page.php' ?>
<?php include 'footer-section.php' ?>